### ISSUE TITLE
can you make this dimmed out?

### ISSUE THREAD

**Issue by 8secz-johndpope** [davodaslanifakor/modaltor#12]
I'm looking for this effect
https://bootstrap-vue.js.org/docs/components/modal/

**Comment by 8secz-johndpope** [comment]
fixed
  <vue-modaltor :bgOverlay="'rgba(0, 0, 0, 0.4)'" :bgPanel="'rgba(255,255,255,1)'"  :visible="embedForm" @hide="hideModal">

you should consider making this default.

**Comment by davodaslanifakor** [comment]
Hi @8secz-johndpope ,
I add all props in this [README.md](https://github.com/davodaslanifakor/modaltor#props-config) file.
