### ISSUE TITLE
Use CDN

### ISSUE THREAD

**Issue by amchconsult** [davodaslanifakor/modaltor#13]
It is not working on CDN. Can you please make small example. 
```
<script src="/vue-modaltor/dist/vue-modaltor.js"></script>
Vue.use(VueModalTor);
```
and it still not working.
Thank you

**Comment by davodaslanifakor** [comment]
@amchconsult 
hi. okay. i'm working on it.

**Comment by iventru** [comment]
It doesn’t work for me either.

**Comment by davodaslanifakor** [comment]
@iventru 
@amchconsult 

for using CDN add below links 

```js

https://cdn.jsdelivr.net/npm/vue-modaltor@1.4.3/dist/vue-modaltor.common.min.js
https://cdn.jsdelivr.net/npm/vue-modaltor@1.4.3/dist/vue-modaltor.min.css
```

and also remember check last -v.
