### ISSUE TITLE
Ability to prevent close by clicking on overlay

### ISSUE THREAD

**Issue by TrendyTim** [davodaslanifakor/modaltor#2]
I still wanted to keep the close by X though, so I removed the $emit('hide') from the click on overlay.

I think it would work better as an option (perhaps even an option to hide the X button as well) to prevent it.

**Comment by davodaslanifakor** [comment]
@TrendyTim 
 add this option see [example](https://github.com/davodaslanifakor/modaltor#example)

**Comment by TrendyTim** [comment]
I updated to the latest  build and got bitten by the overlay click issue again

The :show-close-button="false" still hides the dialog on overlay click though even if one can hide the close button and replace it (which you cant as the slot is within the v-if="showCloseButton".

how about providing a source in the event so 'overlay' or 'closebutton'
