### ISSUE TITLE
Global config for all modals in the app

### ISSUE THREAD

**Issue by Alexxosipov** [davodaslanifakor/modaltor#6]
It will be nice to do a global config for app. Now I need to configure each modal, but, in example, what if I need to do dark background on every modal?

**Comment by davodaslanifakor** [comment]
hi @Alexxosipov   

please update the plugin to "vue-modaltor": "^1.3.8"  

and  add this code for global config

```
import VueModalTor from "vue-modaltor";
Vue.use(VueModalTor, {
  bgPanel: "red"
 ....
});


``
