### ISSUE TITLE
Panel background blurred effect?

### ISSUE THREAD

**Issue by spencerwooo** [davodaslanifakor/modaltor#8]
Great component, thanks. 

I was wondering if you can set the background overlay to a "transparent blur effect". Because I'm currently using it with the overlay set to a transparent color(`rgba(255, 255, 255, 0.8)` to be exact.), and it would be awesome if I can set some sort of blur to the overlay. 

```css
  -webkit-filter: blur(5px);
  -moz-filter: blur(5px);
  -o-filter: blur(5px);
  -ms-filter: blur(5px);
  filter: blur(5px);
```

Above is what you would normally use if you want a blurred background. I don't know how to incorporate this into the component, thanks again.

**Comment by davodaslanifakor** [comment]
Hi,
I'm sorry you waited.
Maybe u can add css for resolve this issues , some like this...
```
.modal-vue-overlay{
    -webkit-filter: blur(5px) !important;
    -moz-filter: blur(5px) !important;
    -o-filter: blur(5px) !important;
    -ms-filter: blur(5px) !important;
    filter: blur(5px) !important;
}
```
And for background-color maybe u want remove this by none property.
